### ISSUE TITLE
Don't downcase_symbolize but underscore instead

### ISSUE THREAD

**Issue by brendanstennett** [drish/hyperb#4]
Particularly troublesome with `inspect_container` outputting options like `publishallports` which kind of gets mangled together without casing.  `publish_all_ports` is more readable

Could introduce ActiveSupport inflector for this but may be overkill.  The implementation is pretty simple, could be a simple copy+paste+credit.

**Comment by drish** [comment]
@brendanstennett you suggesting not to symbolize the response fields anymore, and instead just underscore it ?
I also dislike outputs like `publishallports`, im thinking of transforming `CamelCase` into `camel_case` , the problem is that I found some response fields to be in no specific format, ie:
`Responsefield` , which would be a bit problematic to transform dynamically.

**Comment by drish** [comment]
preparing a pr for it soon

**Comment by brendanstennett** [comment]
@drish No, I do like the symbolized but it would also be nice to see it underscored.  So `"PublishAllPorts" => :publish_all_ports`

**Comment by drish** [comment]
@brendanstennett https://github.com/drish/hyperb/pull/5
